export const ARROW_LEFT = '/icons/arrow-left.svg'
export const THUMBS_UP = '/icons/thumbs-up.svg'
export const ARROW_RIGHT = '/icons/arrow-right.svg'
export const LEVEL_UP = '/icons/level-up.svg'
export const COIN = '/icons/coin.svg'
export const BODY_SHIELD = '/icons/body-shield.svg'
export const BLUE_SHIELD = '/icons/blue-shield.svg'
export const RED_SHIELD = '/icons/shield.svg'
export const COMMANDER = '/icons/commander.svg'
export const ADD_FILL = '/icons/add-fill.svg'
export const DANGER_FILL = '/icons/danger-fill.svg'
export const FILTER_FILL = '/icons/filter-fill.svg'
export const HALF_BODY = '/icons/half-body.svg'
export const GOLD_BUY = '/icons/gold-buy.svg'
export const GOLD_SELL = '/icons/gold-sell.svg'
export const STAKING_GOLD = '/icons/staking-gold.svg'
export const JAMIMAS = '/icons/jamimas.svg'
export const KONUS = '/icons/konus.svg'
export const ADD_ARMY = '/icons/add-army.svg'
export const LOADER = '/icons/loader.svg'
export const COPY = '/icons/copy.svg'
export const ABOUT_US = '/icons/about-us.svg'
export const ALARM = '/icons/alarm.svg'
export const BUCKET_MONEY = '/icons/bucket-money.svg'
export const PEOPLE_TALK = '/icons/people-talk.svg'
export const CHECKLIST = '/icons/checklist.svg'
export const CHECKLIST_CIRCLE = '/icons/checklist-rounded.svg'
export const MONEY = '/icons/money.svg'
export const ARROW_UP_LEVEL = '/icons/arrow-up-level.svg'
export const WHATSAPP = '/icons/whatsapp.svg'
export const DOWNLOAD = '/icons/download.svg'
export const CLOSE = '/icons/close.svg'
export const ARROW_BOTTOM = '/icons/arrow-bottom.svg'
export const HIDE_EYE = '/icons/hide-eye.svg'
export const SHOW_EYE = '/icons/show-eye.svg'
export const CLOSE_BLACK = '/icons/close-black.svg'

/* ======== New Icon for Treasury Army ======== */
export const THUMB_UP_STAR = '/icons/new/thumbs-star.svg'
export const CROWN = '/icons/new/crown.svg'
export const TERMS = '/icons/new/terms.svg'
export const KNIGHT = '/icons/new/knight.svg'
export const KNIGHT_CAPTAIN = '/icons/new/knight-captain.svg'
export const KNIGHT_COMMANDER = '/icons/new/knight-commander.svg'
export const KNIGHT_LIEUTENANT = '/icons/new/knight-lieutenant.svg'
export const BADGE_STAR = '/icons/new/badge-star.svg'
export const KNIGHT_LEGION = '/icons/new/knight-legion.svg'
export const TREASURE_BOX = '/icons/new/treasure-box.svg'
export const DOUBLE_SHIELD = '/icons/new/double-shield.svg'

export const KNIGHT_HISTORY = '/icons/new/knight-history.svg'
export const BUY_GOLD = '/icons/new/buy-gold.svg'
export const SELL_GOLD = '/icons/new/sell-gold.svg'
export const HARVEST = '/icons/new/harvest.svg'

export const SEARCH_FILL = '/icons/search-fill.svg'

export const LEVEL_UP_CIVILLIAN = '/icons/new/level-up-civil.svg'
export const LEVEL_UP_KNIGHT = '/icons/new/level_up_knight.svg'
export const LEVEL_UP_LIEUTENANT = '/icons/new/level_up_lieutenant.svg'
export const LEVEL_UP_COMMANDER = '/icons/new/level_up_commander.svg'
export const LOGOUT = '/icons/logout.svg'

export const CIVILLIAN = '/icons/new/civilian.svg'
/* ======== New Icon for Treasury Army ======== */
